version: "3.9"

services:
  app:
    build:
      context: .
    depends_on:
      - db
      - cache
    ports:
      - ${HOST_APP_PORT:-80}:80
    volumes:
      - .:/app
  db:
    image: postgres:14.1
    ports:
      - ${HOST_POSTGRES_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-demo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
      POSTGRES_DB: ${POSTGRES_DB:-demo}
  cache:
    command: redis-server --requirepass ${REDIS_PASSWORD:-P@ssw0rd}
    image: redis:6.2.6
    ports:
      - ${HOST_REDIS_PORT:-6379}:6379
